### ISSUE TITLE
Bundle install - error - Windows 7  kgio-2.8.0 error Installing

### ISSUE THREAD

**Issue by cmpcb** [Crowdtilt/CrowdtiltOpen#168]
Good Afternoon, i get this error on local instalation Win7.
Is there any solution?

Thanks in advance.
Cheers
## log

Using faraday_middleware (0.9.0)
Using crowdtilt (0.0.1) from git://github.com/msaint/crowdtilt.git (at
Using warden (1.2.1)
Using devise (2.2.4)
Using diff-lcs (1.2.4)
Using dotenv (0.7.0)
Using launchy (2.3.0)
Using email_spec (1.4.0)
Using factory_girl (4.2.0)
Using factory_girl_rails (4.2.1)
Using faker (1.1.2)
Using foreman (0.63.0)
Using friendly_id (4.0.9)
Using iso_country_codes (0.4.1)
Using jquery-rails (3.0.0)
Using jquery-ui-rails (4.0.3)
Installing kgio (2.8.0)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
.

```
    C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb
```

checking for CLOCK_MONOTONIC in time.h... no
checking for CLOCK_MONOTONIC() in time.h... no
checking for clockid_t in time.h... no
checking for clock_gettime() in -lrt... no
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for poll() in poll.h... no
checking for getaddrinfo() in sys/types.h,sys/socket.h,netdb.h... no
getaddrinfo required
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby1.9.3/bin/ruby
        --with-rtlib
        --without-rtlib
        --with-nsllib
        --without-nsllib
        --with-socketlib
        --without-socketlib

Gem files will remain installed in C:/RailsInstaller/Ruby1.9.3/lib/ruby
.1/gems/kgio-2.8.0 for inspection.
Results logged to C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/
0/ext/kgio/gem_make.out
An error occurred while installing kgio (2.8.0), and Bundler cannot con
Make sure that `gem install kgio -v '2.8.0'` succeeds before bundling.

**Comment by DSAMPAT** [comment]
Try this

platforms :ruby do # linux

gem 'unicorn'

end

platforms :mswin do

# gems specific to windows

end

Source: http://stackoverflow.com/questions/10764199/develop-on-windows-run-unicorn-in-production-on-heroku
